# Generated by Django 4.2.5 on 2023-10-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_student_teacher_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='contact',
        ),
    ]
