# Generated by Django 4.2.5 on 2023-10-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_student_contact_remove_teacher_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
