# Generated by Django 4.2.5 on 2023-11-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_assignment_assignmentsubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='course',
            new_name='module',
        ),
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='total_mark',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
