# Generated by Django 4.2.5 on 2023-11-09 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_student_user_remove_teacher_user'),
        ('module', '0004_rename_content_assignment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.CharField(default=''),
        ),
    ]
