# Generated by Django 4.2.5 on 2023-11-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_assignmentsubmission_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='completed_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentcourseenrollment',
            name='enrolled_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='completed_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentcourseenrollment',
            name='enrolled_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
