# Generated by Django 4.2.5 on 2023-11-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0009_quiz_due_date_quiz_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
