# Generated by Django 4.2.5 on 2023-11-18 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_student_user_remove_teacher_user'),
        ('module', '0011_quizsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hangman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('words', models.JSONField(blank=True, null=True)),
                ('hints', models.JSONField(blank=True, null=True)),
                ('total_mark', models.IntegerField(default=50)),
                ('created_time', models.TimeField(auto_now=True)),
                ('created_date', models.DateField(auto_now=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hangman', to='module.module')),
            ],
            options={
                'verbose_name': '9. hangman',
            },
        ),
        migrations.CreateModel(
            name='HangmanSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('completed_time', models.TimeField(auto_now=True)),
                ('completed_date', models.DateField(auto_now=True)),
                ('hangman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_hangman', to='module.hangman')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
            options={
                'verbose_name': '10. Submitted hangman',
            },
        ),
    ]
