# Generated by Django 4.2.5 on 2023-11-22 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_groups_student_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='last_login',
        ),
    ]
